file/urls.py
  
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('homepage/', views.homepage, name = 'homepage'),
    path('register/', views.registerUser, name = 'register'),
    path('login/', views.loginUser, name = 'login'),
    path('logout/', views.logoutUser, name = 'logout'),
    path('example/',views.example,name='example'),
    path('fileload/', views.fileload, name='fileload'),
    path('viewfile/', views.viewfile, name='viewfile'),
    path('search_file/',views.search_file, name='search_file'),
    path('contact/', views.contact,name='contact'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('viewfile/<int:id>', views.delete_doc, name='delete_doc'),
   ]

filesystem/urls.py
from django.contrib import admin
from django.urls import path, include 

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('file.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/models.py
from django.db import models

# Create your models here.
class Docs(models.Model):
	title = models.CharField(max_length=100)
	document_up = models.FileField(upload_to='')

	def __str__(self):
		return self.title

	def delete(self, *args, **kwargs):
		self.document_up.delete()
		super().delete(*args, **kwargs)

file/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Docs


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class DocForm(forms.ModelForm):
    class Meta:
        model = Docs
        fields = ('title', 'document_up')

file/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegisterForm, DocForm
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from .models import Docs
from django.db.models import Q

def index(request):
    return render(request, 'file/index.html', {})

def registerUser(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')

    else:
        form = RegisterForm()
    return render(request, 'file/register.html', {'form':form})

def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if username and password:

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('homepage')
            else:
                messages.error(request, 'Username or Password is Incorrect')
        else:
            messages.error(request, 'Fill out all the fields')

    return render(request, 'file/login.html', {})


def homepage(request):
	return render(request, 'file/homepage.html', {})

def logoutUser(request):
    logout(request)
    return redirect('login')

def example(request):
    return render(request, 'file/example.html', {})

def contact(request):
    return render(request, 'file/contact.html', {} )

def fileload(request):
    context = {}
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['url'] = fs.url(name)
    return render(request, 'file/fileload.html', context)

def viewfile(request):
    dok = Docs.objects.all()
    return render(request, 'file/viewfile.html', {
        'dok': dok
        })

def upload_file(request):
    if request.method == 'POST':
        form = DocForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('viewfile')
    else:
        form = DocForm()
    return render(request, 'file/upload_file.html', {
        'form': form
        })

def delete_doc(request, id):
    if request.method == 'POST':
        doks = Docs.objects.get(id=id)
        doks.delete()
    return redirect('viewfile')

def search_file(request):
    search_post = request.GET.get('search')
    if search_post:
        dok = Docs.objects.filter(title__icontains=search_post)
    else:
        dok = Docs.objects.all()
    return render(request, 'file/viewfile.html', {
        'dok': dok
        })

file/templates/file/contact.html
<DOCTYPE html>
	<html lang = "en">
	<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>БАЙЛАНЫШ</title>
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/back-to-top-scroll-1.css' %}">
        <link rel="stylesheet" href="{% static 'css/back-to-top-scroll.css' %}">
        <link rel="stylesheet" href="{% static 'css/Bold-BS4-Animated-Back-To-Top.css' %}">
        <link rel="stylesheet" href="{% static 'css/cards.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        <link rel="stylesheet" href="{% static 'css/Login-Form-Dark.css' %}">
        <link rel="stylesheet" href="{% static 'css/Pretty-Registration-Form.css' %}">
        <link rel="stylesheet" href="{% static 'css/Sidebar-Menu-1.css' %}">
        <link rel="stylesheet" href="{% static 'css/Sidebar-Menu.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
	</head>
<body style="background-image: url(&quot;{% static 'img/main.jpg' %}&quot;); background-size: cover;
  position: relative;">
    <nav class="navbar navbar-dark navbar-expand-md sticky-top bg-primary">
        <div class="container-fluid"><img src="{% static 'img/logo.png' %}" width="30px" height="30px" alt="10px"><a class="navbar-brand text-center" href="{% url 'index' %}" style="margin: 0px 0px;">КМТУнун иш кагаздары</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div
                class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav text-light ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="{% url 'index' %}">БАШКЫ</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'login' %}">КИРҮҮ</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'register' %}">КАТТАЛУУ</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'example' %}">ҮЛГҮЛӨРҮ</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'contact' %}">БАЙЛАНЫШ</a></li>
                </ul>
            </div>
        </div>
    </nav>
<h1 class="text-center">Байланыш</h1>
<p>Дарек: Кыргыз Республикасы, Бишкек ш., Ч.Айтматов проспекти 66, 5 корпус 5/37 ауд.</p>
<p>Телефон : (0312) 54-70-28</p>
<p>Электрондук почта : ietistt@mail.ru</p>
<p>Иш убактысы: 08:30 - 17:30</p>
<p>Түштөнүү убактысы: 12:20 - 13:00</p>
<p>Эс алуу күндөрү: ишемби, жекшемби</p>
<script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/back-to-top-scroll.js' %}"></script>
    <script src="{% static 'js/Bold-BS4-Animated-Back-To-Top.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="{% static 'js/Sidebar-Menu.js' %}"></script>
</body>

</html>

file/templates/file/example.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>ҮЛГҮЛӨРҮ</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/back-to-top-scroll-1.css' %}">
    <link rel="stylesheet" href="{% static 'css/back-to-top-scroll.css' %}">
    <link rel="stylesheet" href="{% static 'css/Bold-BS4-Animated-Back-To-Top.css' %}">
    <link rel="stylesheet" href="{% static 'css/cards.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="{% static 'css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'css/Pretty-Registration-Form.css' %}">
    <link rel="stylesheet" href="{% static 'css/Sidebar-Menu-1.css' %}">
    <link rel="stylesheet" href="{% static 'css/Sidebar-Menu.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body style="background-image: url(&quot;{% static 'img/main.jpg' %}&quot;); background-size: cover;
  position: relative;">
    <nav class="navbar navbar-dark navbar-expand-md sticky-top bg-primary">
        <div class="container-fluid"><img src="{% static 'img/logo.png' %}" width="30px" height="30px" alt="10px"><a class="navbar-brand text-center" href="{% url 'index' %}" style="margin: 0px 0px;">КМТУнун иш кагаздары</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div
                class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav text-light ml-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="{% url 'index' %}">БАШКЫ</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'login' %}">КИРҮҮ</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'register' %}">КАТТАЛУУ</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'example' %}">ҮЛГҮЛӨРҮ</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'contact' %}">БАЙЛАНЫШ</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <h1 class="text-center">Иш кагаздардын үлгүлөрү</h1>
    <p><a href="{% static 'docs/kafedra_plan.pdf' %}">Кафедранын иш планы</a></p>
    <p><a href="{% static 'docs/kyrgyz_til.pdf' %}">Кыргыз тилин өнүктүрү иш планы </a></p>
    <p><a href="{% static 'docs/mac_oturum.pdf' %}">МАК графигинин билдирүүсү </a></p>
    <p><a href="{% static 'docs/mamsynak.pdf' %}">МАК тапшыруунун билдирүүсү </a></p>
    <p><a href="{% static 'docs/okuu-tarbiya.pdf' %}">Окуу-тарбиялык иштеринин планы </a></p>
    <p><a href="{% static 'docs/practika.pdf' %}">Квалификация алдындагы практиканын билдирүүсү </a></p>
    <div class="scroll-top-wrapper"><span class="scroll-top-inner"><i class="fa fa-arrow-circle-up"></i></span></div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/back-to-top-scroll.js' %}"></script>
    <script src="{% static 'js/Bold-BS4-Animated-Back-To-Top.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="{% static 'js/Sidebar-Menu.js' %}"></script>
</body>

</html>

file/templates/file/fileload.html
<!DOCTYPE html>
<html lang="kg">
<head>
  {% load static %}
	<meta charset="utf-8">
  <title>Жүктөө</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/back-to-top-scroll-1.css' %}">
        <link rel="stylesheet" href="{% static 'css/back-to-top-scroll.css' %}">
        <link rel="stylesheet" href="{% static 'css/Bold-BS4-Animated-Back-To-Top.css' %}">
        <link rel="stylesheet" href="{% static 'css/cards.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        <link rel="stylesheet" href="{% static 'css/Login-Form-Dark.css' %}">
        <link rel="stylesheet" href="{% static 'css/Pretty-Registration-Form.css' %}">
        <link rel="stylesheet" href="{% static 'css/Sidebar-Menu-1.css' %}">
        <link rel="stylesheet" href="{% static 'css/Sidebar-Menu.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    
  </head>
  <body>
    <nav class="navbar navbar-dark navbar-expand-md sticky-top bg-primary float-none">
        <div class="container-fluid"><img src="{% static 'img/logo.png' %}" width="30px" height="30px" alt="10px"><a class="navbar-brand text-center" href="{% url 'index' %}" style="margin: 0px 0px;">КМТУнун иш кагаздары</a>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav text-light ml-auto">
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"></li>
                </ul>
            </div>
        </div>
        </nav>
        <div id="wrapper">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li> <a href="{% url 'homepage' %}" style="color: white;">Уй бети</a></li>
                <li> <a href="{% url 'fileload' %}">Иш кагаздарды жүктөө</a></li>
                <li> <a href="{% url 'upload_file' %}">Uploadfile</a></li>
                <li> <a href="{% url 'viewfile' %}">Иш кагаздарды көрүү</a></li>
                <li> <a href="{% url 'logout' %}">Чыгуу</a></li>
            </ul>
        </div>
        <div class="page-content-wrapper">
            <div class="container-fluid"><a class="btn btn-link" role="button" id="menu-toggle" href="#menu-toggle"><i class="fa fa-bars"></i></a>
                <h2>Upload</h2>
                <form method="post" enctype="multipart/form-data"> 
                    {% csrf_token %}
                    <input type="file" name="document">
                    <button type="submit">Upload file</button>
                    {% if url %}
                    <p>Uploaded file: <a href="{{ url }}">{{ url }}</a></p>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/back-to-top-scroll.js' %}"></script>
    <script src="{% static 'js/Bold-BS4-Animated-Back-To-Top.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="{% static 'js/Sidebar-Menu.js' %}"></script>
  </body>
</html>

file/templates/file/homepage.html
<DOCTYPE html>
	<html lang = "en">
	<head>
		{% load static %}
		<meta charset="UTF-8">
			<title>УЙ БЕТИ</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/back-to-top-scroll-1.css' %}">
        <link rel="stylesheet" href="{% static 'css/back-to-top-scroll.css' %}">
        <link rel="stylesheet" href="{% static 'css/Bold-BS4-Animated-Back-To-Top.css' %}">
        <link rel="stylesheet" href="{% static 'css/cards.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        <link rel="stylesheet" href="{% static 'css/Login-Form-Dark.css' %}">
        <link rel="stylesheet" href="{% static 'css/Pretty-Registration-Form.css' %}">
        <link rel="stylesheet" href="{% static 'css/Sidebar-Menu-1.css' %}">
        <link rel="stylesheet" href="{% static 'css/Sidebar-Menu.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

	</head>
	<body>
		<nav class="navbar navbar-dark navbar-expand-md sticky-top bg-primary float-none">
        <div class="container-fluid"><img src="{% static 'img/logo.png' %}" width="30px" height="30px" alt="10px"><a class="navbar-brand text-center" href="{% url 'index' %}" style="margin: 0px 0px;">КМТУнун иш кагаздары</a>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav text-light ml-auto">
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"></li>
                </ul>
            </div>
        </div>
        </nav>
     <div id="wrapper">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li> <a href="{% url 'homepage' %}" style="color: white;">Уй бети</a></li>
                <li> <a href="{% url 'upload_file' %}">Иш кагаздарды жүктөө</a></li>
                <li> <a href="{% url 'viewfile' %}">Иш кагаздарды көрүү</a></li>
                <li> <a href="{% url 'logout' %}">Чыгуу</a></li>
            </ul>
        </div>
        <div class="page-content-wrapper">
            <div class="container-fluid"><a class="btn btn-link" role="button" id="menu-toggle" href="#menu-toggle"><i class="fa fa-bars"></i></a>
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <h1 class="text-center">{{user.username}}, кош келиңиз !</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/back-to-top-scroll.js' %}"></script>
    <script src="{% static 'js/Bold-BS4-Animated-Back-To-Top.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="{% static 'js/Sidebar-Menu.js' %}"></script>
	</body>
	</html>

file/templates/file/upload_file.html
<DOCTYPE html>
	<html lang = "en">
	<head>
		{% load static %}
		<meta charset="UTF-8">
			<title>Жүктөө</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/back-to-top-scroll-1.css' %}">
        <link rel="stylesheet" href="{% static 'css/back-to-top-scroll.css' %}">
        <link rel="stylesheet" href="{% static 'css/Bold-BS4-Animated-Back-To-Top.css' %}">
        <link rel="stylesheet" href="{% static 'css/cards.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        <link rel="stylesheet" href="{% static 'css/Login-Form-Dark.css' %}">
        <link rel="stylesheet" href="{% static 'css/Pretty-Registration-Form.css' %}">
        <link rel="stylesheet" href="{% static 'css/Sidebar-Menu-1.css' %}">
        <link rel="stylesheet" href="{% static 'css/Sidebar-Menu.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

	</head>
	<body>
		<nav class="navbar navbar-dark navbar-expand-md sticky-top bg-primary float-none">
        <div class="container-fluid"><img src="{% static 'img/logo.png' %}" width="30px" height="30px" alt="10px"><a class="navbar-brand text-center" href="{% url 'index' %}" style="margin: 0px 0px;">КМТУнун иш кагаздары</a>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav text-light ml-auto">
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"></li>
                </ul>
            </div>
        </div>
        </nav>
     <div id="wrapper">
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li> <a href="{% url 'homepage' %}" style="color: white;">Уй бети</a></li>
                <li> <a href="{% url 'upload_file' %}">Иш кагаздарды жүктөө</a></li>
                <li> <a href="{% url 'viewfile' %}">Иш кагаздарды көрүү</a></li>
                <li> <a href="{% url 'logout' %}">Чыгуу</a></li>
            </ul>
        </div>
        <div class="page-content-wrapper">
            <div class="container-fluid"><a class="btn btn-link" role="button" id="menu-toggle" href="#menu-toggle"><i class="fa fa-bars"></i></a>
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <h2 style="text-align: center;">Документтерди жүктөө </h2>
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div id="div_id_title" class="form-group">
                                    <label for="id_title" class="requiredField">
                                        Документтин аты
                                    </label>
                                    <div class>
                                        <input type="text" name="title" maxlength="100" class="textinput textInput form-control" required id="id_title">
                                    </div>
                                </div>
                                <div id="div_id_document_up" class="form-group">
                                    <label for="id_document_up" class="requiredField" style="width: 102; background-color: #007BFF; border-radius: 5px; padding: 6px; font-size: 15px; color: white; text-align: center;">
                                        Документти таңдаңыз
                                    </label>
                                    <div class>
                                        <input type="file" name="document_up" class="clearablefileinput form-control-file" required id="id_document_up" style="display: none">
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary">Жүктөө</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/back-to-top-scroll.js' %}"></script>
    <script src="{% static 'js/Bold-BS4-Animated-Back-To-Top.js' %}"></script>
    <script src="{% static 'js/bs-init.js' %}"></script>
    <script src="{% static 'js/Sidebar-Menu.js' %}"></script>
	</body>
	</html>